### PR TITLE
Updating readme with named instance example

### PR DESCRIPTION
**Pull request by pvanhouten**
The typical connection string for a named instance will refer to the server as "server\instance".  Seriate instead requires that you use the server name or IP and a port to access the named instance of SQL Server.

The appropriate port for your named instance can be found in SQL Server Configuration Manager under the SQL Server Network Configuration -> Protocols for [named instance] -> TCP/IP (properties) -> IP Addresses tab -> IPAll group -> TCP Dynamic Ports value.

Thought some more detail in the docs would be helpful to those getting started using seriate who might trip up on the connection when using a named instance.

### CODE REVIEW

**Comment by rniemeyer** [comment]
@pvanhouten - Thanks for the README update Phil.  That seems like a reliable option for talking to a named instance. There is one other way: you can specify the server as `server: yourServer\\instanceName`. You do also need to ensure that the SQL Server Browser service is running (and possibly firewall considerations) for this to work.  Would you mind adding this information in addition to what you already added to the PR?

**Comment by pvanhouten** [comment]
I was struggling to get the `server\\instance` convention to work.  In that case, I think it's import to know that doing `.` as the server doesn't work (I usually just do `.\instance`).  It seemed like only DNS resolvable names worked for the server name.  Switching it over to `localhost\\instance` seemed to make it a little happier, but it still wouldn't connect for me.  Must have been that I wasn't running the SQL Server Browser service.  I'll update the PR.  Thanks, Ryan!

**Comment by pvanhouten** [comment]
I updated the README with that additional information.  Let me know if there are any additional questions or issues.  Thanks!

**Comment by rniemeyer** [comment]
Thanks @pvanhouten !

**Pull request merged**
